import mongoose, { Schema } from 'mongoose';
import { IStudent } from '../types/index.js';

const studentSchema = new Schema<IStudent>({
  studentId: {
    type: String,
    unique: true,
    required: false, // Will be auto-generated by pre-save hook
  },
  userId: {
    type: Schema.Types.ObjectId,
    ref: 'User',
    required: true,
  },
  name: {
    type: String,
    required: [true, 'Name is required'],
    trim: true,
  },
  email: {
    type: String,
    required: [true, 'Email is required'],
    unique: true,
    trim: true,
    lowercase: true,
  },
  phone: {
    type: String,
    required: [true, 'Phone is required'],
    trim: true,
  },
  class: {
    type: String,
    required: [true, 'Class is required'],
  },
  section: {
    type: String,
  },
  dateOfBirth: {
    type: Date,
    required: [true, 'Date of birth is required'],
  },
  admissionDate: {
    type: Date,
    required: [true, 'Admission date is required'],
  },
  gender: {
    type: String,
    enum: ['Male', 'Female', 'Other'],
    required: [true, 'Gender is required'],
  },
  address: {
    type: String,
  },
  parent: {
    type: String,
    required: [true, 'Parent name is required'],
  },
  parentPhone: {
    type: String,
    required: [true, 'Parent phone is required'],
  },
  parentEmail: {
    type: String,
  },
  previousSchool: {
    type: String,
  },
  status: {
    type: String,
    enum: ['Active', 'Inactive', 'Graduated', 'Transferred'],
    default: 'Active',
  },
}, {
  timestamps: true,
});

// Generate studentId before saving (runs before validation)
studentSchema.pre('save', async function(next) {
  if (!this.studentId) {
    try {
      // Count existing students to get the next number
      const count = await mongoose.model('Student').countDocuments();
      this.studentId = `S${String(count + 1).padStart(3, '0')}`;
      
      // Ensure uniqueness by checking if the generated ID exists
      const exists = await mongoose.model('Student').findOne({ studentId: this.studentId });
      if (exists) {
        // If exists, increment and try again
        const newCount = await mongoose.model('Student').countDocuments();
        this.studentId = `S${String(newCount + 1).padStart(3, '0')}`;
      }
    } catch (error) {
      return next(error as Error);
    }
  }
  next();
});

const Student = mongoose.model<IStudent>('Student', studentSchema);

export default Student;

