import mongoose, { Schema } from 'mongoose';
import { ITeacher } from '../types/index.js';

const teacherSchema = new Schema<ITeacher>({
  teacherId: {
    type: String,
    unique: true,
    required: false, // Will be auto-generated by pre-save hook
  },
  userId: {
    type: Schema.Types.ObjectId,
    ref: 'User',
    required: true,
  },
  name: {
    type: String,
    required: [true, 'Name is required'],
    trim: true,
  },
  email: {
    type: String,
    required: [true, 'Email is required'],
    unique: true,
    trim: true,
    lowercase: true,
  },
  phone: {
    type: String,
    required: [true, 'Phone is required'],
    trim: true,
  },
  subject: {
    type: String,
    required: [true, 'Subject is required'],
  },
  experience: {
    type: String,
    required: [true, 'Experience is required'],
  },
  qualification: {
    type: String,
  },
  address: {
    type: String,
  },
  city: {
    type: String,
  },
  country: {
    type: String,
  },
  joinDate: {
    type: Date,
    default: Date.now,
  },
  status: {
    type: String,
    enum: ['Active', 'Inactive', 'On Leave'],
    default: 'Active',
  },
}, {
  timestamps: true,
});

// Generate teacherId before saving
teacherSchema.pre('save', async function(next) {
  if (!this.teacherId) {
    const count = await mongoose.model('Teacher').countDocuments();
    this.teacherId = `T${String(count + 1).padStart(3, '0')}`;
  }
  next();
});

const Teacher = mongoose.model<ITeacher>('Teacher', teacherSchema);

export default Teacher;

