import mongoose, { Schema } from 'mongoose';

export interface ITransaction extends mongoose.Document {
  _id: string;
  transactionId?: string;
  type: 'Income' | 'Expense';
  category: string;
  description: string;
  amount: number;
  date: Date;
  time?: string;
  status: string;
  paymentMethod?: string;
  expenseId?: mongoose.Types.ObjectId | string;
  feeId?: mongoose.Types.ObjectId | string;
  payrollId?: mongoose.Types.ObjectId | string;
  referenceId?: string;
  createdBy?: string;
  createdAt: Date;
  updatedAt: Date;
}

const transactionSchema = new Schema<ITransaction>({
  transactionId: {
    type: String,
    unique: true,
    required: false, // Will be auto-generated by pre-save hook
  },
  type: {
    type: String,
    enum: ['Income', 'Expense'],
    required: true,
  },
  category: {
    type: String,
    required: true,
  },
  description: {
    type: String,
    required: true,
  },
  amount: {
    type: Number,
    required: true,
    min: 0,
  },
  date: {
    type: Date,
    required: true,
    default: Date.now,
  },
  time: {
    type: String,
  },
  status: {
    type: String,
    default: 'Pending',
  },
  paymentMethod: {
    type: String,
    enum: ['Cash', 'Bank Transfer', 'Cheque', 'Online', 'Credit Card'],
  },
  expenseId: {
    type: Schema.Types.ObjectId,
    ref: 'Expense',
  },
  feeId: {
    type: Schema.Types.ObjectId,
    ref: 'FeeCollection',
  },
  payrollId: {
    type: Schema.Types.ObjectId,
    ref: 'Payroll',
  },
  referenceId: {
    type: String,
  },
  createdBy: {
    type: String,
  },
}, {
  timestamps: true,
});

// Generate transactionId before saving (runs before validation)
transactionSchema.pre('save', async function(next) {
  if (!this.transactionId) {
    try {
      // Count existing transactions that have transactionId
      const existingTransactions = await mongoose.model('Transaction').countDocuments({
        transactionId: { $exists: true, $ne: null, $nin: ['', null] }
      });
      
      // Generate transactionId: TXN000001, TXN000002, etc.
      const nextNumber = existingTransactions + 1;
      this.transactionId = `TXN${String(nextNumber).padStart(6, '0')}`;
      
      // Ensure uniqueness by checking if this transactionId already exists
      const existing = await mongoose.model('Transaction').findOne({ transactionId: this.transactionId });
      if (existing && existing._id.toString() !== this._id.toString()) {
        // If exists and it's not the current document, find the next available number
        const lastTransaction = await mongoose.model('Transaction')
          .findOne({ transactionId: { $exists: true, $ne: null, $nin: ['', null] } })
          .sort({ transactionId: -1 });
        
        if (lastTransaction && lastTransaction.transactionId) {
          const match = lastTransaction.transactionId.match(/^TXN(\d+)$/);
          if (match) {
            const lastNumber = parseInt(match[1], 10);
            this.transactionId = `TXN${String(lastNumber + 1).padStart(6, '0')}`;
          }
        }
      }
    } catch (error: any) {
      return next(error);
    }
  }
  next();
});

const Transaction = mongoose.model<ITransaction>('Transaction', transactionSchema);

export default Transaction;

